version: '3'
services:
  repetier:
    privileged: true
    environment:
    build: .
    ports:
      - "3344:3344"
    volumes:
      - data:/var/lib/Repetier-Server
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0"

volumes:
  data:
    driver: "local"